services:
  majestikmagik:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
Transform: AWS::Serverless-2016-10-31